export interface ImageContent {
  type: 'image_url'
  image_url: {
    url: string
  }
}

import type { RPGGameState, RPGRound, RPGAgent } from './rpg'

export interface TextContent {
  type: 'text'
  text: string
}

export interface Tool {
  id: string
  name: string
  description: string
  icon: string
  pattern: string
}

export const availableTools: Tool[] = [
  {
    id: 'create_image',
    name: 'Create Image',
    description: 'Generate images from text descriptions using AI',
    icon: 'image',
    pattern: '@create_image'
  },
  {
    id: 'create_video',
    name: 'Create Video',
    description: 'Generate videos from text prompts with optional image reference',
    icon: 'video',
    pattern: '@create_video'
  },
  {
    id: 'edit_image',
    name: 'Edit Image',
    description: 'Edit existing images using AI based on text prompts',
    icon: 'wand-2',
    pattern: '@edit_image'
  },
  {
    id: 'vision',
    name: 'Vision',
    description: 'Analyze images and videos using vision-capable models',
    icon: 'eye',
    pattern: '@vision'
  },
  {
    id: 'agentic_image',
    name: 'Agentic Image',
    description: 'Generate images with automatic quality verification and iterative refinement',
    icon: 'sparkles',
    pattern: '@agentic_image'
  },
  {
    id: 'agentic_video',
    name: 'Agentic Video',
    description:
      'Generate videos with automatic quality verification and iterative refinement using vision models',
    icon: 'clapperboard',
    pattern: '@agentic_video'
  },
  {
    id: 'rpg',
    name: 'RPG Game',
    description: 'Turn-based collaborative creation with multiple AI agents',
    icon: 'gamepad-2',
    pattern: '@rpg'
  }
]

export type ToolStatus = 'pending' | 'success' | 'error'

export interface VisionVerification {
  satisfied: boolean
  issues: string[]
  suggestedEdit: string
  recommendedStrategy?: 'fresh' | 'progressive' | 'targeted'
}

// Image Analysis types for intelligent editing
export interface FaceInfo {
  id: number
  location: string
  description: string
}

export interface ClothingInfo {
  item: string
  color: string
  location: string
}

export interface ImageAnalysis {
  hasFaces: boolean
  faces: FaceInfo[]
  clothing: ClothingInfo[]
  background: string
  keyObjects: string[]
  totalElements: number
  preservationInstructions: string
}

export interface AgenticIteration {
  iterationNumber: number
  image: string
  editPrompt: string
  visionFeedback: VisionVerification
  imageAnalysis?: ImageAnalysis
}

export interface AgenticVideoIteration {
  iterationNumber: number
  video: string
  editPrompt: string
  visionFeedback: VisionVerification
}

export interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string | (TextContent | ImageContent)[]
  timestamp: number
  model?: string
  images?: string[] // Base64 encoded images (user uploads)
  activeTool?: string // ID of the tool being used (e.g., 'create_image')
  generatedImages?: string[] // Base64 encoded images generated by AI
  generatedVideos?: string[] // Base64 encoded videos generated by AI
  toolStatus?: ToolStatus // Status of tool execution
  agenticIterations?: AgenticIteration[] // Iterations from agentic image generation
  agenticVideoIterations?: AgenticVideoIteration[] // Iterations from agentic video generation
  imageAnalysis?: ImageAnalysis // Analysis results for display (agentic_image/video)
  // RPG Game fields
  rpgState?: RPGGameState // Game state for RPG mode
  rpgRound?: RPGRound // Current round for RPG mode
  rpgAgents?: RPGAgent[] // Active agents in RPG game
}

export interface Conversation {
  id: string
  title: string
  messages: Message[]
  createdAt: number
  updatedAt: number
}

export const IMAGE_MODELS = [
  {
    id: 'glm-image',
    name: 'GLM Image',
    url: 'https://api.novita.ai/v3/async/glm-image'
  }
] as const

export const VIDEO_RESOLUTIONS = [
  { id: '480p', name: '480p', width: 854, height: 480 },
  { id: '720p', name: '720p', width: 1280, height: 720 }
] as const

export interface Settings {
  apiKey: string
  instructions: string
  selectedProvider: string
  selectedModel: string
  selectedImageModel: string
  selectedVisionModel: string
  selectedVideoResolution: string
  maxAgenticIterations: number
}

export interface Model {
  id: string
  name: string
  cost: number
  providerId: string
  providerName: string
  providerApi?: string
  max_tokens?: number
  modalities?: {
    input: string[]
    output: string[]
  }
}

export function supportsVision(model: Model): boolean {
  return model.modalities?.input?.includes('image') ?? false
}

export function supportsVideo(model: Model): boolean {
  return model.modalities?.input?.includes('video') ?? false
}

export * from './playground'
