export interface ImageContent {
  type: 'image_url'
  image_url: {
    url: string
  }
}

export interface TextContent {
  type: 'text'
  text: string
}

export interface Tool {
  id: string
  name: string
  description: string
  icon: string
  pattern: string
}

export const availableTools: Tool[] = [
  {
    id: 'create_image',
    name: 'Create Image',
    description: 'Generate images from text descriptions using AI',
    icon: 'image',
    pattern: '@create_image'
  }
]

export type ToolStatus = 'pending' | 'success' | 'error'

export interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string | (TextContent | ImageContent)[]
  timestamp: number
  model?: string
  images?: string[] // Base64 encoded images (user uploads)
  activeTool?: string // ID of the tool being used (e.g., 'create_image')
  generatedImages?: string[] // Base64 encoded images generated by AI
  toolStatus?: ToolStatus // Status of tool execution
}

export interface Conversation {
  id: string
  title: string
  messages: Message[]
  createdAt: number
  updatedAt: number
}

export const IMAGE_MODELS = [
  { id: 'z-image-turbo', name: 'Z Image Turbo', url: 'https://chutes-z-image-turbo.chutes.ai/generate' },
  { id: 'Qwen-Image-2512', name: 'Qwen Image 2512', url: 'https://chutes-qwen-image-2512.chutes.ai/generate' },
  { id: 'chroma', name: 'Chroma', url: 'https://chutes-chroma.chutes.ai/generate' },
  { id: 'hunyuan-image-3', name: 'Hunyuan Image 3', url: 'https://chutes-hunyuan-image-3.chutes.ai/generate' }
] as const

export interface Settings {
  apiKey: string
  instructions: string
  selectedModel: string
  selectedImageModel: string
}

export interface Model {
  id: string
  name: string
  cost: number
}
